### ISSUE TITLE
New feature: amplitude dampening

### ISSUE THREAD

**Issue by TysonRayJones** [QuEST-Kit/QuEST#115]

**Comment by nfwvogt** [comment]
Is that supposed to correspond to zero-temperature qubit damping, where a qubit decays with rate (or probability) p from state 1 to state 0?
Or in the Kraus language the operation that gives two Kraus operators:
[[0, sqrt(p)],
[0, 0]]
and
[[1, 0],
[0, sqrt(1-p)]]

I'm asking because we just noticed that we (@HQSquantumsimulations) need to have this kind of damping for some simulations we need to run and put an implementation of a corresponding applyOneQubitDamping into a [fork](https://github.com/HQSquantumsimulations/QuEST/tree/develop_damping) and were considering submitting a pull request.

**Comment by TysonRayJones** [comment]
Yes! That's fantastic news, we'll check it out. We may be a little slow, since we'll use this opportunity to set up a protocol for reviewing and accepting external pull requests.

**Comment by nfwvogt** [comment]
No worries, I'll just submit a proper pull request then. Once you have set up the protocol, just let me know what else you need.

**Comment by TysonRayJones** [comment]
This has been tested, tweaked and merged into master!
