### ISSUE TITLE
unit tests do not pass 

### ISSUE THREAD

**Issue by dempips** [QuEST-Kit/QuEST#218]
contents of build/Testing/Temporary/LastTest.log after executing 'make test'.
```
`Start testing: Feb 01 10:34 GMT
----------------------------------------------------------
1/2 Testing: build
1/2 Test: build
Command: "/usr/bin/make" "QuESTTest"
Directory: /home/pi/Desktop/QuEST/build
"build" start time: Feb 01 10:34 GMT
Output:
----------------------------------------------------------
[100%] Built target QuEST
[100%] Built target QuESTTest
<end of output>
Test time =   0.19 sec
----------------------------------------------------------
Test Passed.
"build" end time: Feb 01 10:34 GMT
"build" time elapsed: 00:00:00
----------------------------------------------------------

2/2 Testing: unit
2/2 Test: unit
Command: "/usr/bin/python3.7" "-m" "QuESTTest" "-Q" "/home/pi/Desktop/QuEST/build/QuEST" "-l" "/home/pi/Desktop/QuEST/build/QuESTLog.log" "unit"
Directory: /home/pi/Desktop/QuEST/utilities
"unit" start time: Feb 01 10:34 GMT
Output:
----------------------------------------------------------
Running tests essential: .F.......

Passed 8 of 9 tests, 1 failed.

EXECUTION ENVIRONMENT:
Running locally on one node
Number of ranks is 1
OpenMP enabled
Number of threads available is 4
Precision: size of qreal is 8 bytes
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/Desktop/QuEST/utilities/QuESTTest/__main__.py", line 103, in <module>
    raise ValueError("System failed essential qubit initalisation tests, impossible to continue!")
ValueError: System failed essential qubit initalisation tests, impossible to continue!
<end of output>
Test time =   0.15 sec
----------------------------------------------------------
Test Fail Reason:
Error regular expression found in output. Regex=[Error]
"unit" end time: Feb 01 10:34 GMT
"unit" time elapsed: 00:00:00
`

``pi@raspberrypi:~/Desktop/QuEST/build $ cat QuESTLog.log 
Test initPlusState:Plus  State Vec Failed: 
Result :                     Expected: 

(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)
(-0.0000000000000,0.0000000000000) (-0.0000000000000,0.0000000000000)`

Any ideas as to why its not able to execute this test?
Final words: Running on Raspian (Raspberry Pi 4) OS, 'cmake ..' compiled and 'make' compiled.

**Comment by TysonRayJones** [comment]
Hi Chris,

The python tests had some outstanding issues, but we've since moved to C++ based tests using Catch2. These are currently on the [develop](https://github.com/QuEST-Kit/QuEST/tree/develop) branch, to be merged into master and a new release very soon. I'd disregard these results, and run the new tests on develop in the same way.

Thanks,
Tyson

**Comment by dempips** [comment]
I followed your instructions and was able to compile the code on my Mac (Clang 11) and unit tests passed however on my RPi4 and Jetson Nano with GCC 8.3 and GCC 7.4 respectively, which gcc version should I be using?

**Comment by TysonRayJones** [comment]
Those are all supported versions. What exactly isn't working? Try to get me as much detail as you can, so that I can try to replicate your problem.

**Comment by dempips** [comment]
Output of make test for Jetson (sorry for the bad photo).

![1580905390733](https://user-images.githubusercontent.com/8439221/73841358-5459bd80-4812-11ea-9ab7-a9b0d39bd341.jpg)

**Comment by dempips** [comment]
Sample Output of make for RPi4, after 50% of the way through when it starts to compile the test modules. 
![1580905596140](https://user-images.githubusercontent.com/8439221/73841692-02656780-4813-11ea-9e24-235957b9c921.jpg)

I'm not sure where I've gone wrong.

**Comment by TysonRayJones** [comment]
Your first errors (`Child aborted`) actually seem to be a problem with the exceptions that the QuEST unit tests are intentionally throwing, in order to check user-validation. I've seen the same problem on POWER8 - it's likely a C++ compiler version problem. Try this, which directly runs the Catch2 test executable and disables checking these user-validations.
```bash
mkdir build && cd build
cmake .. -DTESTING=ON
make
./tests/tests -c "correctness"
```
I can see though that `calcTotalProb` seems to have just failed - that is very strange indeed! Can you check whether that's still the case in the above test?

By the way, unit-test runtime is dominated by testing of `mixMultiQubitKrausMap` and there's no reason for that particular function to fail if all the others pass. So to speed up your tests, change the last command above to
```bash
./tests/tests exclude:mixMultiQubitKrausMap -c "correctness"
```

-------------------

Your latter RPi4 problem also seems a compiler version problem - your compiler seems to have issues with Catch2, and with QuEST test's use of C++14 complex types. I don't know much about Raspberry Pi, but I can see you're using gcc-7, which [should be compatible](https://gcc.gnu.org/projects/cxx-status.html#cxx14). Can you please try this (forcing use of `g++` for the C++ tests):
```bash
mkdir build && cd build
cmake .. -DTESTING=ON -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
make
make test
```

**Comment by TysonRayJones** [comment]
Hi Chris,
Any luck on this?

**Comment by dempips** [comment]
No luck with that the RPi4. I stopped development with the nano for now, will touch upon it later. 
When I run the tutorial example, it works up to 23 qubits or so and when it shows the probability of the states for specific qubits, the results seem to be correct. 
It seems that the tests would pass if the tutorial example functions as required. 
I used the QuEST library in a Benchmark against more barebones code and rewrote the tutorial example and it seemed to work up to 22 qubits but then crashed from a Seg fault. Not sure if my code had the leak but couldn't allocate more than 22 qubits.
Hope this information was helpful.

**Comment by TysonRayJones** [comment]
Actually, I wouldn't trust that just because the limited functions used in the tutorial example work, that the rest of the API runs fine on the platform - there can always be insidious platform and function specific bugs!

A 22-qubit register at double-precision (QuEST's default) costs only 64 MiB, and shouldn't cause any issues in QuEST. One possible explanation is that your own code was allocating things on the stack (e.g. using fixed-size arrays) and so exceeded the stack limit, which is around this size (though is system specific). 

In any case, this does not seem to be a QuEST issue. Cheers!
