### ISSUE TITLE
illegal instruction (core dumped)

### ISSUE THREAD

**Issue by amandalqy** [QuEST-Kit/QuEST#264]
Hi, when I run the excecutable named demo, the following errors occur:illegal instruction (core dumped). Does anyone know the reason? If it is because the version of cpu, what is the minimum version of cpu required by Quest ? Thanks!

**Comment by TysonRayJones** [comment]
Hi Amanda,

This may relate to issue #259, caused by a default compile flag for AVX, which may be a facility that your CPU doesn't support.
If that's the case, you can merely disable the flag. Just remove [line 205](https://github.com/QuEST-Kit/QuEST/blob/c8b954abd1fd0a9f1a2e8fb98efed700f2ff75bf/QuEST/CMakeLists.txt#L205) of `QuEST/CMakeLists.txt`

What CPU are you using by the way? This might help me better understand the issue.

Thanks,
Tyson

**Comment by amandalqy** [comment]
Hi Tyson, thanks for your reply! The CPU I use is Intel Celeron(R) CPU J1900. Thanks again!

**Comment by TysonRayJones** [comment]
Ah yep, indeed that has no AVX support. Glad to help!
