### ISSUE TITLE
Hamiltonian Arithmetic

### ISSUE THREAD

**Issue by ghost** [QuEST-Kit/QuEST#316]
I have been looking through the documentation to try find a way to do arithmetic with Hamiltonians, and have not found anything.
To be clear, I wish to create a Hamiltonian of a similar form to H = A + c*B**2 where A and B are both Pauli Sums. I was hoping there would be an automated way of adding and multiplying PauliSums, as oppose to computing the Pauli expansion of H by hand.
Is there a way to do this in QuEST?

**Comment by TysonRayJones** [comment]
Hi Joe,

QuEST doesn't have any facilities for symbolic simplification. However, if you have access to Mathematica, this possible in [QuESTlink](https://github.com/QTechTheory/QuESTLink) through the `SimplifyPaulis` function.
![image](https://user-images.githubusercontent.com/29574749/144953235-34908dbb-4e97-4ffe-9b2a-c24ab54648c8.png)

You can use its `GetPauliSumFromCoeffs` function to generate a symbolic Hamiltonian (like above) from the same Pauli Hamiltonian file accepted by QuEST's [`createPauliHamilFromFile`](https://quest-kit.github.io/QuEST/group__type.html#gaa77376c5e3518186eb085f37826d6008).

Unfortunately this would be quite a sophisticated facility to add to QuEST, since even a natural syntax to specify the symbolic Hamiltonian expression would be difficult in C.

I hope this helps!
