### ISSUE TITLE
inverse quantum Fourier Transform?

### ISSUE THREAD

**Issue by soronzonbold** [QuEST-Kit/QuEST#320]
Hey all, I am fairly new to QuEST. So is there an inverse QFT class or is there a different way to do that by using QFT in QuEST since I only saw QFT?

Thank you very much.

**Comment by TysonRayJones** [comment]
Hi there,

Unfortunately there isn't currently an inverse QFT function, though it'd be straightforward to implement one. 
I should regrettably mention that the existing [`applyQFT()`](https://quest-kit.github.io/QuEST/group__operator.html#ga9bc8c4ab44f8233b5766208a0b1c0776) function is planned to be changed in the next release, to reverse its circuit and remove the SWAP gates. Also, due to a strange behaviour in `applyPhaseGate` that we're still investigating, `applyQFT()` is actually currently _less_ efficient than simulating the circuit gate-by-gate for certain system sizes!

So, I would actually encourage you to just implement the QFT an inverse QFT circuits yourself, as needed. Because the majority of the gates happen to be embarassingly parallel when simulated in distributed mode, your gate-by-gate simulation will still be very efficient. 

Hope this helps!

**Comment by soronzonbold** [comment]
It helps, thank you very much.
